// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDR0QokFdSu1MUa9qOim_FoFTqxDwp_RlI',
    appId: '1:7365321212:android:b9e3bd5c04374568d19279',
    messagingSenderId: '7365321212',
    projectId: 'educore-a97b1',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZfBvbLNGKGdytze5SbQMBEyd8vnm8U7s',
    appId: '1:7365321212:ios:b83825eb22d45cf4d19279',
    messagingSenderId: '7365321212',
    projectId: 'educore-a97b1',
    iosBundleId: 'com.example.educore',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB2Vxb0bF0X_EQLTFIPbib3VV5-3_wudXU',
    appId: '1:7365321212:web:17814ba17cda5e79d19279',
    messagingSenderId: '7365321212',
    projectId: 'educore-a97b1',
    authDomain: 'educore-a97b1.firebaseapp.com',
    measurementId: 'G-866D08J9LB',
  );
}
